version: '2'
services:
  otg_config_db1:
      image: mariadb:10.1
      container_name: otg_config_db1
      restart: always
      volumes:
        - ./db1/initdb/:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=S3cretP@ssw0rd
        - MYSQL_DATABASE=login
  otg_config_web1:
      build:
        context: .
        dockerfile: Dockerfile-web1
      container_name: otg_config_web1
      restart: always
      volumes:
        - ./web1/:/var/www/html
      expose:
        - "9000"
      links:
        - otg_config_db1:otg_config_db1
  otg_config_engin1:
      build:
        context: .
        dockerfile: Dockerfile-engin1
      container_name: otg_config_engin1
      restart: always
      volumes_from:
        - otg_config_web1
      links:
        - otg_config_db1:otg_config_db1
      ports:
        - 52021:80
      command: [nginx-debug, '-c', '/etc/nginx/conf/nginx.conf']

  otg_config_engin2:
    build:
      context: .
      dockerfile: Dockerfile-engin2
    container_name: otg_config_engin2
    restart: always
    ports:
      - 52022:80