version: '2'
services:

  otg_ident_web1:
      build:
        context: .
        dockerfile: Dockerfile-web1
      container_name: otg_ident_web1
      restart: always
      volumes:
        - ./web1/:/var/www/html
      expose:
        - "9000"
  otg_ident_engin1:
      build:
        context: .
        dockerfile: Dockerfile-engin1
      container_name: otg_ident_engin1
      restart: always
      volumes_from:
        - otg_ident_web1
      ports:
        - 52031:80
      command: [nginx-debug, '-c', '/etc/nginx/conf/nginx.conf']

  otg_ident_web2:
      build:
        context: .
        dockerfile: Dockerfile-web2
      container_name: otg_ident_web2
      restart: always
      volumes:
        - ./web2/:/var/www/html
      expose:
        - "9000"
  otg_ident_engin2:
      build:
        context: .
        dockerfile: Dockerfile-engin2
      container_name: otg_ident_engin2
      restart: always
      volumes_from:
        - otg_ident_web2
      ports:
        - 52032:80
      command: [nginx-debug, '-c', '/etc/nginx/conf/nginx.conf']