version: '2'
services:

  otg_crypst_db1:
      image: mariadb:10.1
      container_name: otg_crypst_db1
      restart: always
      volumes:
        - ./db1/initdb/:/docker-entrypoint-initdb.d
        - ./db1/data/:/var/lib/mysqldf
      environment:
        - MYSQL_ROOT_PASSWORD=S3cret99P@ssw0rd
        - MYSQL_DATABASE=acc_manage_site2
  otg_crypst_web1:
      build:
        context: .
        dockerfile: Dockerfile-web1
      container_name: otg_crypst_web1
      restart: always
      volumes:
        - ./web1/:/var/www/html
      expose:
        - "9000"
      links:
        - otg_crypst_db1:otg_crypst_db1        
  otg_crypst_engin1:
      build:
        context: .
        dockerfile: Dockerfile-engin1
      container_name: otg_crypst_engin1
      restart: always
      volumes_from:
        - otg_crypst_web1
      ports:
        - 52091:80
      links:
        - otg_crypst_db1:otg_crypst_db1          
      command: [nginx-debug, '-c', '/etc/nginx/conf/nginx.conf']