version: '2'
services:

  otg_authn_engin1:
    build:
      context: .
      dockerfile: Dockerfile-engin1
    container_name: otg_authn_engin1
    restart: always
    ports:
      - 52041:8080
    command: ["catalina.sh", "run"]

  otg_authn_db2:
      image: mariadb:10.1
      container_name: otg_authn_db2
      restart: always
      volumes:
        - ./db2/initdb/:/docker-entrypoint-initdb.d
        - ./db2/data/:/var/lib/mysqldf
      environment:
        - MYSQL_ROOT_PASSWORD=S3cretP@ssw0rd
        - MYSQL_DATABASE=login
  otg_authn_web2:
      build:
        context: .
        dockerfile: Dockerfile-web2
      container_name: otg_authn_web2
      restart: always
      volumes:
        - ./web2/:/var/www/html
      expose:
        - "9000"
      links:
        - otg_authn_db2:otg_authn_db2
  otg_config_engin2:
      build:
        context: .
        dockerfile: Dockerfile-engin2
      container_name: otg_authn_engin2
      restart: always
      volumes_from:
        - otg_authn_web2
      ports:
        - 52042:80
      links:
        - otg_authn_db2:otg_authn_db2        